[package]
name = "unreal-pak-mod-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
json-patch = "3.0.1"
regex = "1.11.1"
serde = "1.0.215"
serde_json = {version = "1.0.133", features = ["preserve_order"]}
toml = "0.8.19"
